#!/usr/bin/env node
// Slice the shared catalog tree into per-locale widget modules (Contract C42).
//
//   i18n/locales/en/widget.json     -> widget/src/catalog-en.ts   (INLINED into widget.js)
//   i18n/locales/<code>/widget.json -> widget/src/locales/<code>.ts (lazy dist/locales/<code>.js)
//
// Both outputs are generated, gitignored, and rewritten from scratch on every
// build; the catalogs under `i18n/locales/` are the only source of truth and
// this script never writes to them.
//
// Shape (C42): a FLAT map of full dotted keys to strings — `export default
// { "widget.form.subject": "Betreff", … }`. Keys absent from a locale are
// OMITTED, not emitted empty: the runtime falls back per key to the inlined
// `en` map (C35 rule 6), so an omitted key renders English while an empty
// string would render nothing.
//
// `en` lives OUTSIDE `src/locales/` on purpose: `loadLocale()` dynamic-imports
// `./locales/${code}.js`, and Rollup turns that template into a chunk for every
// module in that directory. Keeping `en` out of it is what stops the inlined
// English catalog from being split back out into a chunk widget.js would have
// to fetch.

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const WIDGET_DIR = resolve(HERE, "..");
const REPO_ROOT = resolve(WIDGET_DIR, "..");
const CATALOG_DIR = join(REPO_ROOT, "i18n", "locales");
const LOCALES_JSON = join(REPO_ROOT, "i18n", "locales.json");
const OUT_LAZY_DIR = join(WIDGET_DIR, "src", "locales");
const OUT_EN = join(WIDGET_DIR, "src", "catalog-en.ts");
const OUT_CHUNKS = join(WIDGET_DIR, "src", "locale-chunks.ts");
const NS = "widget";

const HEADER =
  `// GENERATED by widget/scripts/slice-locales.mjs from i18n/locales/<code>/${NS}.json` +
  " (Contract C42) -- do not edit, do not commit.\n";

/** Nested catalog object -> flat dotted keys, dropping `_meta`. */
function flatten(node, prefix, out) {
  for (const [key, value] of Object.entries(node)) {
    if (key === "_meta") continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      flatten(value, path, out);
    } else if (typeof value === "string") {
      out[path] = value;
    }
  }
  return out;
}

function readCatalog(code) {
  const file = join(CATALOG_DIR, code, `${NS}.json`);
  try {
    return flatten(JSON.parse(readFileSync(file, "utf8")), "", {});
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw new Error(`${file}: ${err.message}`);
  }
}

function moduleSource(map) {
  // Sorted keys so the emitted chunk is byte-stable across runs (the size
  // oracle reads these files; churn there would be indistinguishable from a
  // real size change).
  const body = Object.keys(map)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
    .join("\n");
  // Typed as an index signature, not `as const`: the runtime looks keys up by
  // a computed string, which literal key types reject (TS7053).
  return `${HEADER}\nconst catalog: Record<string, string> = {\n${body}\n};\n\nexport default catalog;\n`;
}

const localeTable = JSON.parse(readFileSync(LOCALES_JSON, "utf8"));
const table = localeTable.locales;
const codes = table.map((l) => l.code);

const en = readCatalog("en");
if (!en) throw new Error(`missing source catalog: i18n/locales/en/${NS}.json`);
if (Object.keys(en).length === 0) {
  throw new Error(`i18n/locales/en/${NS}.json has no keys — the widget would render raw keys`);
}
writeFileSync(OUT_EN, moduleSource(en), "utf8");

// Rewrite the lazy directory from scratch so a locale removed from
// i18n/locales.json cannot leave a stale chunk behind in dist/.
rmSync(OUT_LAZY_DIR, { recursive: true, force: true });
mkdirSync(OUT_LAZY_DIR, { recursive: true });
writeFileSync(
  join(OUT_LAZY_DIR, ".gitignore"),
  "# Generated per-locale slices (widget/scripts/slice-locales.mjs). Never committed.\n*.ts\n",
  "utf8",
);

let emitted = 0;
let translated = 0;
for (const code of codes) {
  if (code === "en") continue;
  const map = readCatalog(code);
  if (!map) {
    console.warn(`slice-locales: no catalog for ${code} — skipping`);
    continue;
  }
  // Emit the chunk even when the catalog is still an untranslated skeleton:
  // the OUTPUT FILE SET must not change the first time someone runs
  // /1-translate, because `dist/` is committed and vendored by copy.
  const own = Object.fromEntries(Object.entries(map).filter(([k]) => k in en));
  writeFileSync(join(OUT_LAZY_DIR, `${code}.ts`), moduleSource(own), "utf8");
  emitted++;
  if (Object.keys(own).length > 0) translated++;
}

// The loader map. Every `import()` specifier is a STRING LITERAL, which is
// what lets Rollup emit one chunk per locale under vite's lib mode (a
// template-literal import compiles to a runtime path-guessing helper and emits
// no chunks at all — measured 2026-09-06). It doubles as the whitelist: a
// locale with no entry here simply cannot be imported, so no computed
// specifier ever reaches `import()`.
const loaders = codes
  .filter((c) => c !== "en")
  .map((c) => `  ${JSON.stringify(c)}: () => import("./locales/${c}.js"),`)
  .join("\n");
const rtl = table.filter((l) => l.dir === "rtl").map((l) => l.code);
const dict = (o) =>
  "{\n" +
  Object.entries(o)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n") +
  "\n}";
writeFileSync(
  OUT_CHUNKS,
  `${HEADER}\nimport type { Catalog } from "./i18n.js";\n\n` +
    "// The widget's runtime projection of the C34 table (i18n/locales.json).\n" +
    "// It holds the four facts the widget uses and NOT the endonyms or DeepL\n" +
    "// targets in widget/src/locales.gen.ts: the widget renders no language\n" +
    "// switcher, and that array cannot be tree-shaken out of the bundle (its\n" +
    "// LOCALE_CODES / BY_CODE initializers call .map, which Rollup must assume\n" +
    "// is impure), so importing it would spend ~1.9 KB of a 7.4 KB page-load\n" +
    "// budget on data no widget code reads. Both files are generated from the\n" +
    "// same i18n/locales.json on every build, so they cannot drift.\n\n" +
    "/** Lazy per-locale catalog chunks, keyed by C34 code. `en` is inlined, so it has no entry. */\n" +
    "export const LOADERS: Record<string, () => Promise<{ default: Catalog }>> = {\n" +
    `${loaders}\n};\n\n` +
    "/** Codes whose script runs right-to-left (C34 `dir`). */\n" +
    `export const RTL: readonly string[] = ${JSON.stringify(rtl)};\n\n` +
    "/** Tags whose correct bundle is not their base language; matched longest-prefix-first. */\n" +
    `export const TAG_OVERRIDES: Readonly<Record<string, string>> = ${dict(localeTable.overrides)};\n\n` +
    "/** Where a bare language code goes when the language ships only regional bundles. */\n" +
    `export const BARE_DEFAULTS: Readonly<Record<string, string>> = ${dict(localeTable.bare_defaults)};\n\n` +
    `export const DEFAULT_LOCALE = ${JSON.stringify(localeTable.default)};\n`,
  "utf8",
);

const stale = readdirSync(OUT_LAZY_DIR).filter((f) => f.endsWith(".ts")).length;
console.log(
  `slice-locales: ${Object.keys(en).length} en keys inlined; ` +
    `${emitted} locale chunk(s) emitted (${translated} with at least one key, ${stale} files)`,
);
