#!/usr/bin/env python3
"""Generate the three runtime locale tables from i18n/locales.json (Contract C41).

Outputs (all committed, all carrying a GENERATED header):
  admin-ui/src/i18n/locales.gen.ts
  widget/src/locales.gen.ts
  crates/feedbackmonk-i18n/src/locales.gen.rs

Usage:
  python scripts/i18n/gen-locales.py          # write the three files
  python scripts/i18n/gen-locales.py --check  # exit 1 if any file differs from what would be written

The `i18n-catalog-integrity` oracle calls `--check`, so a hand edit to a generated file is caught on
every commit. Python 3.8+, stdlib only.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / "i18n" / "locales.json"
OUTPUTS = {
    "ts_admin": ROOT / "admin-ui" / "src" / "i18n" / "locales.gen.ts",
    "ts_widget": ROOT / "widget" / "src" / "locales.gen.ts",
    "rs": ROOT / "crates" / "feedbackmonk-i18n" / "src" / "locales.gen.rs",
}
HEADER = "GENERATED by scripts/i18n/gen-locales.py from i18n/locales.json (Contract C34/C41) -- do not edit."


def load() -> dict:
    data = json.loads(TABLE.read_text(encoding="utf-8"))
    codes = [l["code"] for l in data["locales"]]
    assert len(codes) == len(set(codes)), "duplicate locale code"
    assert data["default"] in codes, "default locale missing from table"
    for l in data["locales"]:
        assert l["dir"] in ("ltr", "rtl"), l
        assert l["base"] is None or l["base"] in codes, l
    for k, v in {**data["overrides"], **data["bare_defaults"]}.items():
        assert v in codes, f"override {k} -> {v} not shipped"
    return data


def ts_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def render_ts(data: dict) -> str:
    lines = [f"// {HEADER}", "", "export type Dir = 'ltr' | 'rtl';", "",
             "export interface LocaleEntry {",
             "  /** Canonical short code (C34). Used for catalog dirs, data-locale, submitter_locale, <html lang>. */",
             "  readonly code: string;",
             "  /** Native display name (endonym). */",
             "  readonly name: string;",
             "  readonly dir: Dir;",
             "  /** DeepL target_lang, or null when DeepL has no target (English fallback by design). */",
             "  readonly deepl: string | null;",
             "}", "",
             f"export const DEFAULT_LOCALE = {ts_string(data['default'])};", "",
             "/** The 31 shipped locales, English first, in switcher order. */",
             "export const LOCALES: readonly LocaleEntry[] = ["]
    for l in data["locales"]:
        lines.append(f"  {{ code: {ts_string(l['code'])}, name: {ts_string(l['name'])}, dir: {ts_string(l['dir'])}, deepl: {json.dumps(l['deepl'])} }},")
    lines += ["];", "",
              "/** Tags whose correct bundle is not their base language; matched longest-prefix-first. */",
              "export const TAG_OVERRIDES: Readonly<Record<string, string>> = {"]
    for k, v in data["overrides"].items():
        lines.append(f"  {ts_string(k)}: {ts_string(v)},")
    lines += ["};", "",
              "/** Where a bare language code goes when the language ships only regional bundles. */",
              "export const BARE_DEFAULTS: Readonly<Record<string, string>> = {"]
    for k, v in data["bare_defaults"].items():
        lines.append(f"  {ts_string(k)}: {ts_string(v)},")
    lines += ["};", "",
              "export const LOCALE_CODES: readonly string[] = LOCALES.map((l) => l.code);",
              "const BY_CODE: Readonly<Record<string, LocaleEntry>> = Object.fromEntries(LOCALES.map((l) => [l.code, l]));",
              "// OWN properties only. `code in BY_CODE` walks the prototype chain, so `constructor`",
              "// (the one Object.prototype name that survives canonicalisation) passed the gate and",
              "// localeByCode returned the Function itself -- R-SEC finding, collab-20260907-034037.",
              "const hasShippedCode = (code: string): boolean => Object.prototype.hasOwnProperty.call(BY_CODE, code);",
              "export const localeByCode = (code: string): LocaleEntry | undefined => (hasShippedCode(code) ? BY_CODE[code] : undefined);",
              "export const isShippedLocale = (code: string): boolean => hasShippedCode(code);",
              ""]
    return "\n".join(lines)


def rs_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def render_rs(data: dict) -> str:
    lines = [f"// {HEADER}", "",
             "use crate::{Dir, LocaleEntry};", "",
             f"pub const DEFAULT_LOCALE: &str = {rs_string(data['default'])};", "",
             "/// The 31 shipped locales, English first, in switcher order (Contract C34).",
             "pub const LOCALES: &[LocaleEntry] = &["]
    for l in data["locales"]:
        d = "Dir::Rtl" if l["dir"] == "rtl" else "Dir::Ltr"
        deepl = f"Some({rs_string(l['deepl'])})" if l["deepl"] else "None"
        lines.append(f"    LocaleEntry {{ code: {rs_string(l['code'])}, name: {rs_string(l['name'])}, dir: {d}, deepl: {deepl} }},")
    lines += ["];", "",
              "/// Tags whose correct bundle is not their base language; matched longest-prefix-first.",
              "pub const TAG_OVERRIDES: &[(&str, &str)] = &["]
    for k, v in data["overrides"].items():
        lines.append(f"    ({rs_string(k)}, {rs_string(v)}),")
    lines += ["];", "",
              "/// Where a bare language code goes when the language ships only regional bundles.",
              "pub const BARE_DEFAULTS: &[(&str, &str)] = &["]
    for k, v in data["bare_defaults"].items():
        lines.append(f"    ({rs_string(k)}, {rs_string(v)}),")
    lines += ["];", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    data = load()
    rendered = {
        "ts_admin": render_ts(data),
        "ts_widget": render_ts(data),
        "rs": render_rs(data),
    }
    drift = []
    for key, path in OUTPUTS.items():
        content = rendered[key]
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                drift.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    if check:
        if drift:
            print("DRIFT: generated locale tables differ from i18n/locales.json:")
            for d in drift:
                print(f"  {d}")
            print("Run: python scripts/i18n/gen-locales.py")
            return 1
        print(f"OK: {len(OUTPUTS)} generated locale tables match i18n/locales.json ({len(data['locales'])} locales)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
