// GENERATED by scripts/i18n/gen-locales.py from i18n/locales.json (Contract C34/C41) -- do not edit.

use crate::{Dir, LocaleEntry};

pub const DEFAULT_LOCALE: &str = "en";

/// The 31 shipped locales, English first, in switcher order (Contract C34).
pub const LOCALES: &[LocaleEntry] = &[
    LocaleEntry { code: "en", name: "English", dir: Dir::Ltr, deepl: Some("EN-US") },
    LocaleEntry { code: "de", name: "Deutsch", dir: Dir::Ltr, deepl: Some("DE") },
    LocaleEntry { code: "fr", name: "Français", dir: Dir::Ltr, deepl: Some("FR") },
    LocaleEntry { code: "es", name: "Español", dir: Dir::Ltr, deepl: Some("ES") },
    LocaleEntry { code: "pt-BR", name: "Português (Brasil)", dir: Dir::Ltr, deepl: Some("PT-BR") },
    LocaleEntry { code: "ja", name: "日本語", dir: Dir::Ltr, deepl: Some("JA") },
    LocaleEntry { code: "zh-CN", name: "简体中文", dir: Dir::Ltr, deepl: Some("ZH-HANS") },
    LocaleEntry { code: "ko", name: "한국어", dir: Dir::Ltr, deepl: Some("KO") },
    LocaleEntry { code: "zh-HK", name: "繁體中文（香港）", dir: Dir::Ltr, deepl: Some("ZH-HANT") },
    LocaleEntry { code: "zh-TW", name: "繁體中文（台灣）", dir: Dir::Ltr, deepl: Some("ZH-HANT") },
    LocaleEntry { code: "ga", name: "Gaeilge", dir: Dir::Ltr, deepl: None },
    LocaleEntry { code: "nl", name: "Nederlands", dir: Dir::Ltr, deepl: Some("NL") },
    LocaleEntry { code: "lv", name: "Latviešu", dir: Dir::Ltr, deepl: Some("LV") },
    LocaleEntry { code: "ru", name: "Русский", dir: Dir::Ltr, deepl: Some("RU") },
    LocaleEntry { code: "uk", name: "Українська", dir: Dir::Ltr, deepl: Some("UK") },
    LocaleEntry { code: "pt-PT", name: "Português (Portugal)", dir: Dir::Ltr, deepl: Some("PT-PT") },
    LocaleEntry { code: "pl", name: "Polski", dir: Dir::Ltr, deepl: Some("PL") },
    LocaleEntry { code: "bg", name: "Български", dir: Dir::Ltr, deepl: Some("BG") },
    LocaleEntry { code: "it", name: "Italiano", dir: Dir::Ltr, deepl: Some("IT") },
    LocaleEntry { code: "fi", name: "Suomi", dir: Dir::Ltr, deepl: Some("FI") },
    LocaleEntry { code: "tr", name: "Türkçe", dir: Dir::Ltr, deepl: Some("TR") },
    LocaleEntry { code: "cs", name: "Čeština", dir: Dir::Ltr, deepl: Some("CS") },
    LocaleEntry { code: "sv", name: "Svenska", dir: Dir::Ltr, deepl: Some("SV") },
    LocaleEntry { code: "el", name: "Ελληνικά", dir: Dir::Ltr, deepl: Some("EL") },
    LocaleEntry { code: "fa", name: "فارسی", dir: Dir::Rtl, deepl: None },
    LocaleEntry { code: "hu", name: "Magyar nyelv", dir: Dir::Ltr, deepl: Some("HU") },
    LocaleEntry { code: "id", name: "Bahasa Indonesia", dir: Dir::Ltr, deepl: Some("ID") },
    LocaleEntry { code: "ml", name: "മലയാളം", dir: Dir::Ltr, deepl: None },
    LocaleEntry { code: "is", name: "Íslenska", dir: Dir::Ltr, deepl: None },
    LocaleEntry { code: "si", name: "සිංහල", dir: Dir::Ltr, deepl: None },
    LocaleEntry { code: "sk", name: "Slovenčina", dir: Dir::Ltr, deepl: Some("SK") },
];

/// Tags whose correct bundle is not their base language; matched longest-prefix-first.
pub const TAG_OVERRIDES: &[(&str, &str)] = &[
    ("zh-Hans", "zh-CN"),
    ("zh-Hant", "zh-TW"),
    ("zh-SG", "zh-CN"),
    ("zh-MO", "zh-HK"),
    ("pt-AO", "pt-PT"),
    ("pt-MZ", "pt-PT"),
    ("pt-CV", "pt-PT"),
    ("pt-GW", "pt-PT"),
    ("pt-ST", "pt-PT"),
    ("pt-TL", "pt-PT"),
    ("pt-MO", "pt-PT"),
];

/// Where a bare language code goes when the language ships only regional bundles.
pub const BARE_DEFAULTS: &[(&str, &str)] = &[
    ("pt", "pt-BR"),
    ("zh", "zh-CN"),
];
