// GENERATED by scripts/i18n/gen-locales.py from i18n/locales.json (Contract C34/C41) -- do not edit.

export type Dir = 'ltr' | 'rtl';

export interface LocaleEntry {
  /** Canonical short code (C34). Used for catalog dirs, data-locale, submitter_locale, <html lang>. */
  readonly code: string;
  /** Native display name (endonym). */
  readonly name: string;
  readonly dir: Dir;
  /** DeepL target_lang, or null when DeepL has no target (English fallback by design). */
  readonly deepl: string | null;
}

export const DEFAULT_LOCALE = "en";

/** The 31 shipped locales, English first, in switcher order. */
export const LOCALES: readonly LocaleEntry[] = [
  { code: "en", name: "English", dir: "ltr", deepl: "EN-US" },
  { code: "de", name: "Deutsch", dir: "ltr", deepl: "DE" },
  { code: "fr", name: "Français", dir: "ltr", deepl: "FR" },
  { code: "es", name: "Español", dir: "ltr", deepl: "ES" },
  { code: "pt-BR", name: "Português (Brasil)", dir: "ltr", deepl: "PT-BR" },
  { code: "ja", name: "日本語", dir: "ltr", deepl: "JA" },
  { code: "zh-CN", name: "简体中文", dir: "ltr", deepl: "ZH-HANS" },
  { code: "ko", name: "한국어", dir: "ltr", deepl: "KO" },
  { code: "zh-HK", name: "繁體中文（香港）", dir: "ltr", deepl: "ZH-HANT" },
  { code: "zh-TW", name: "繁體中文（台灣）", dir: "ltr", deepl: "ZH-HANT" },
  { code: "ga", name: "Gaeilge", dir: "ltr", deepl: null },
  { code: "nl", name: "Nederlands", dir: "ltr", deepl: "NL" },
  { code: "lv", name: "Latviešu", dir: "ltr", deepl: "LV" },
  { code: "ru", name: "Русский", dir: "ltr", deepl: "RU" },
  { code: "uk", name: "Українська", dir: "ltr", deepl: "UK" },
  { code: "pt-PT", name: "Português (Portugal)", dir: "ltr", deepl: "PT-PT" },
  { code: "pl", name: "Polski", dir: "ltr", deepl: "PL" },
  { code: "bg", name: "Български", dir: "ltr", deepl: "BG" },
  { code: "it", name: "Italiano", dir: "ltr", deepl: "IT" },
  { code: "fi", name: "Suomi", dir: "ltr", deepl: "FI" },
  { code: "tr", name: "Türkçe", dir: "ltr", deepl: "TR" },
  { code: "cs", name: "Čeština", dir: "ltr", deepl: "CS" },
  { code: "sv", name: "Svenska", dir: "ltr", deepl: "SV" },
  { code: "el", name: "Ελληνικά", dir: "ltr", deepl: "EL" },
  { code: "fa", name: "فارسی", dir: "rtl", deepl: null },
  { code: "hu", name: "Magyar nyelv", dir: "ltr", deepl: "HU" },
  { code: "id", name: "Bahasa Indonesia", dir: "ltr", deepl: "ID" },
  { code: "ml", name: "മലയാളം", dir: "ltr", deepl: null },
  { code: "is", name: "Íslenska", dir: "ltr", deepl: null },
  { code: "si", name: "සිංහල", dir: "ltr", deepl: null },
  { code: "sk", name: "Slovenčina", dir: "ltr", deepl: "SK" },
];

/** Tags whose correct bundle is not their base language; matched longest-prefix-first. */
export const TAG_OVERRIDES: Readonly<Record<string, string>> = {
  "zh-Hans": "zh-CN",
  "zh-Hant": "zh-TW",
  "zh-SG": "zh-CN",
  "zh-MO": "zh-HK",
  "pt-AO": "pt-PT",
  "pt-MZ": "pt-PT",
  "pt-CV": "pt-PT",
  "pt-GW": "pt-PT",
  "pt-ST": "pt-PT",
  "pt-TL": "pt-PT",
  "pt-MO": "pt-PT",
};

/** Where a bare language code goes when the language ships only regional bundles. */
export const BARE_DEFAULTS: Readonly<Record<string, string>> = {
  "pt": "pt-BR",
  "zh": "zh-CN",
};

export const LOCALE_CODES: readonly string[] = LOCALES.map((l) => l.code);
const BY_CODE: Readonly<Record<string, LocaleEntry>> = Object.fromEntries(LOCALES.map((l) => [l.code, l]));
// OWN properties only. `code in BY_CODE` walks the prototype chain, so `constructor`
// (the one Object.prototype name that survives canonicalisation) passed the gate and
// localeByCode returned the Function itself -- R-SEC finding, collab-20260907-034037.
const hasShippedCode = (code: string): boolean => Object.prototype.hasOwnProperty.call(BY_CODE, code);
export const localeByCode = (code: string): LocaleEntry | undefined => (hasShippedCode(code) ? BY_CODE[code] : undefined);
export const isShippedLocale = (code: string): boolean => hasShippedCode(code);
